#!/bin/sh
# $Id$

HOST_OS=`uname -s`
if test "x${HOST_OS}" = "xDarwin"; then
	LIBTOOLIZE=glibtoolize
elif test "x${HOST_OS}" = "xLinux"; then
	LIBTOOLIZE=libtoolize
fi
set -x
${LIBTOOLIZE} --force --copy
aclocal -I m4 
autoheader
rm -f m4/config.guess # XXX
automake --foreign --add-missing --copy
autoconf

# EOF
